"""Curated YouTube niche catalog (seed data).

This is the single place to extend the recommended niches. On startup the app
seeds the `niches` table from here if it is empty; the API serves from the DB so
niches are fully backend/database-driven and extensible without a frontend change.

Curated for YouTube *creator* lead-gen. `popularity` doubles as a GLOBAL priority
score (higher = more valuable lead niche); Auto mode discovers high-priority niches
first so the daily API quota is spent on the best niches before it runs out.
"""
from __future__ import annotations

# category -> [(name, popularity, recommended)]  (popularity = global priority)
CATALOG: dict[str, list[tuple[str, int, bool]]] = {
    "AI & Data": [
        ('Artificial Intelligence', 189, True),
        ('AI Tools', 188, True),
        ('ChatGPT', 187, True),
        ('Generative AI', 186, True),
        ('Machine Learning', 185, True),
        ('Data Science', 184, True),
    ],
    "Programming & Development": [
        ('Programming', 183, True),
        ('Python', 182, True),
        ('JavaScript', 181, True),
        ('Web Development', 180, True),
        ('App Development', 179, True),
        ('Software Development', 178, True),
        ('Coding Tutorials', 177, True),
        ('DevOps', 176, True),
    ],
    "Tech & Gadgets": [
        ('Cybersecurity', 175, True),
        ('Cloud Computing', 174, True),
        ('Tech Reviews', 173, True),
        ('Gadgets', 172, True),
        ('Smartphones', 171, True),
        ('Laptop Reviews', 170, True),
        ('PC Builds', 169, True),
        ('Gaming PCs', 168, True),
        ('Software Reviews', 167, True),
        ('Electronics', 166, True),
    ],
    "Emerging Tech": [
        ('Home Automation', 82, True),
        ('Smart Home', 81, True),
        ('Robotics', 80, True),
        ('3D Printing', 79, True),
        ('Blockchain', 78, True),
        ('Web3', 77, True),
        ('AR', 76, True),
        ('VR', 75, True),
        ('IoT', 74, True),
    ],
    "SaaS & Startups": [
        ('Entrepreneurship', 215, True),
        ('Business', 214, True),
        ('Business Ideas', 213, True),
        ('Startups', 212, True),
        ('SaaS', 211, True),
        ('Startup Stories', 165, True),
        ('Founder Interviews', 164, True),
        ('Case Studies', 163, True),
        ('Success Stories', 162, True),
        ('Failure Stories', 161, True),
    ],
    "Marketing": [
        ('Digital Marketing', 225, True),
        ('SEO', 224, True),
        ('Social Media Marketing', 223, True),
        ('Content Marketing', 222, True),
        ('Affiliate Marketing', 221, True),
        ('Email Marketing', 220, True),
        ('Facebook Ads', 219, True),
        ('Google Ads', 218, True),
        ('Marketing', 217, True),
        ('Sales', 216, True),
        ('Influencers', 151, True),
    ],
    "Online Business & Money-Making": [
        ('Online Business', 210, True),
        ('E-commerce', 209, True),
        ('Shopify', 208, True),
        ('Amazon FBA', 207, True),
        ('Dropshipping', 206, True),
        ('Print on Demand', 205, True),
        ('Freelancing', 204, True),
        ('Side Hustles', 203, True),
    ],
    "Finance & Investing": [
        ('Personal Finance', 202, True),
        ('Finance', 201, True),
        ('Investing', 200, True),
        ('Stock Market', 199, True),
        ('Trading', 198, True),
        ('Crypto', 197, True),
        ('Bitcoin', 196, True),
        ('Ethereum', 195, True),
        ('Mutual Funds', 194, True),
        ('Passive Income', 193, True),
        ('Money Saving', 192, True),
        ('Wealth Building', 191, True),
    ],
    "Career & Productivity": [
        ('Career Advice', 160, True),
        ('Resume Tips', 159, True),
        ('Interview Preparation', 158, True),
        ('Productivity', 157, True),
        ('Self Improvement', 156, True),
        ('Personal Development', 155, True),
        ('Motivation', 154, True),
        ('Study Tips', 133, True),
    ],
    "Education & Learning": [
        ('Public Speaking', 153, True),
        ('Communication Skills', 152, True),
        ('Education', 137, True),
        ('Online Learning', 136, True),
        ('English Learning', 135, True),
        ('Language Learning', 134, True),
        ('Mathematics', 132, True),
    ],
    "Health & Fitness": [
        ('Fitness', 131, True),
        ('Gym', 130, True),
        ('Bodybuilding', 129, True),
        ('Weight Loss', 128, True),
        ('Nutrition', 127, True),
        ('Healthy Eating', 126, True),
        ('Yoga', 125, True),
        ('Meditation', 124, True),
        ('Mental Health', 123, True),
        ('Running', 24, True),
        ('Cycling', 23, True),
    ],
    "Sports": [
        ('Sports', 22, True),
        ('Sports Training', 21, True),
        ('Football', 20, True),
        ('Cricket', 19, True),
        ('Basketball', 18, True),
        ('Badminton', 17, True),
        ('Chess', 16, True),
    ],
    "Gaming": [
        ('Gaming', 15, True),
        ('Minecraft', 14, True),
        ('Roblox', 13, True),
        ('Free Fire', 12, True),
        ('BGMI', 11, True),
        ('PUBG', 10, True),
        ('Valorant', 9, True),
        ('Fortnite', 8, True),
        ('GTA V', 7, True),
        ('Call of Duty', 6, True),
        ('Esports', 5, True),
        ('Game Reviews', 4, True),
        ('Game Streaming', 3, True),
    ],
    "Travel": [
        ('Travel', 106, True),
        ('Travel Vlogs', 105, True),
        ('Budget Travel', 104, True),
        ('Luxury Travel', 103, True),
    ],
    "Food & Cooking": [
        ('Food', 114, True),
        ('Cooking', 113, True),
        ('Recipes', 112, True),
        ('Baking', 111, True),
        ('Street Food', 110, True),
        ('Restaurant Reviews', 109, True),
        ('Coffee', 108, True),
        ('Tea', 107, True),
    ],
    "Lifestyle & Vlogs": [
        ('Lifestyle', 54, True),
        ('Daily Vlogs', 53, True),
        ('Family Vlogs', 52, True),
    ],
    "Beauty & Fashion": [
        ('Beauty', 122, True),
        ('Makeup', 121, True),
        ('Skincare', 120, True),
        ('Hair Care', 119, True),
        ('Fashion', 118, True),
        ("Men's Fashion", 117, True),
        ("Women's Fashion", 116, True),
        ('Luxury Fashion', 115, True),
    ],
    "Photography & Video": [
        ('Photography', 149, True),
        ('Videography', 148, True),
        ('Video Editing', 147, True),
        ('Filmmaking', 146, True),
        ('Cinematography', 145, True),
        ('Drone Photography', 144, True),
    ],
    "Design & Creative": [
        ('Graphic Design', 143, True),
        ('UI UX Design', 142, True),
        ('Animation', 141, True),
        ('3D Animation', 140, True),
        ('Motion Graphics', 139, True),
    ],
    "Home & DIY": [
        ('Interior Design', 102, True),
        ('Home Decor', 101, True),
        ('DIY', 66, True),
        ('Crafts', 65, True),
        ('Woodworking', 64, True),
        ('Gardening', 63, True),
    ],
    "Pets & Family": [
        ('Pets', 62, True),
        ('Dog Training', 61, True),
        ('Cat Care', 60, True),
        ('Parenting', 59, True),
        ('Baby Care', 58, True),
        ('Relationships', 57, True),
        ('Dating Advice', 56, True),
        ('Wedding Planning', 55, True),
    ],
    "Real Estate & Architecture": [
        ('Real Estate', 190, True),
        ('Architecture', 100, True),
        ('Construction', 99, True),
        ('Interior Architecture', 98, True),
    ],
    "Professional & Medical": [
        ('Law', 97, True),
        ('Legal Advice', 96, True),
        ('Medical Education', 95, True),
        ('Doctors', 94, True),
        ('Dentists', 93, True),
        ('Nursing', 92, True),
        ('Physiotherapy', 91, True),
        ('Psychology', 90, True),
    ],
    "Science & Space": [
        ('Science', 51, True),
        ('Physics', 50, True),
        ('Chemistry', 49, True),
        ('Biology', 48, True),
        ('Astronomy', 47, True),
        ('Space', 46, True),
    ],
    "Knowledge & News": [
        ('History', 45, True),
        ('Geography', 44, True),
        ('Documentaries', 43, True),
        ('Current Affairs', 42, True),
        ('News', 41, True),
        ('News Analysis', 40, True),
        ('Politics', 39, True),
        ('Economics', 38, True),
    ],
    "Media & Entertainment": [
        ('YouTube Creators', 150, True),
        ('Podcasts', 37, True),
        ('Podcast', 36, True),
        ('Interviews', 35, True),
        ('Book Reviews', 34, True),
        ('Movie Reviews', 33, True),
        ('TV Show Reviews', 32, True),
        ('Anime', 2, True),
        ('Comics', 1, True),
    ],
    "Music & Performance": [
        ('Music Production', 138, True),
        ('Music', 31, True),
        ('Singing', 30, True),
        ('Guitar Lessons', 29, True),
        ('Piano Lessons', 28, True),
        ('Dance', 27, True),
        ('Stand-up Comedy', 26, True),
        ('Magic', 25, True),
    ],
    "Automotive": [
        ('Automobiles', 73, True),
        ('Car Reviews', 72, True),
        ('Bike Reviews', 71, True),
        ('Electric Vehicles', 70, True),
        ('Motorcycles', 69, True),
        ('Luxury Cars', 68, True),
        ('Automotive News', 67, True),
    ],
    "Engineering & Energy": [
        ('Engineering', 89, True),
        ('Mechanical Engineering', 88, True),
        ('Civil Engineering', 87, True),
        ('Chemical Engineering', 86, True),
        ('Environmental Science', 85, True),
        ('Renewable Energy', 84, True),
        ('Solar Energy', 83, True),
    ],
}


def iter_catalog():
    """Yield (name, category, popularity, recommended) for every niche."""
    for category, items in CATALOG.items():
        for name, popularity, recommended in items:
            yield name, category, popularity, recommended
