"""Curated YouTube niche catalog (seed data).

This is the single place to extend the recommended niches. On startup the app
seeds the `niches` table from here if it is empty; the API serves from the DB so
niches are fully backend/database-driven and extensible without a frontend change.
"""
from __future__ import annotations

# category -> [(name, popularity, recommended)]
CATALOG: dict[str, list[tuple[str, int, bool]]] = {
    "Technology": [
        ("Artificial Intelligence", 98, True),
        ("Machine Learning", 92, True),
        ("Programming", 95, True),
        ("Web Development", 90, True),
        ("Mobile Development", 82, False),
        ("Software Development", 88, True),
        ("Cybersecurity", 86, True),
        ("Cloud Computing", 80, False),
        ("Data Science", 89, True),
        ("AI Tools", 94, True),
        ("Robotics", 72, False),
        ("Engineering", 70, False),
    ],
    "Business": [
        ("Entrepreneurship", 91, True),
        ("Marketing", 90, True),
        ("Finance", 88, True),
        ("Investing", 87, True),
        ("Real Estate", 78, False),
        ("Startups", 85, True),
        ("Sales", 75, False),
        ("E-commerce", 84, True),
        ("Crypto", 83, True),
        ("B2B SaaS", 74, False),
        ("Productivity", 79, False),
    ],
    "Education": [
        ("Online Learning", 80, True),
        ("Science", 82, True),
        ("Mathematics", 74, False),
        ("History", 72, False),
        ("Language Learning", 77, False),
        ("Documentary", 70, False),
    ],
    "Health & Fitness": [
        ("Fitness", 90, True),
        ("Nutrition", 84, True),
        ("Yoga", 76, False),
        ("Mental Health", 82, True),
        ("Bodybuilding", 78, False),
    ],
    "Lifestyle": [
        ("Travel", 88, True),
        ("Photography", 83, True),
        ("Cooking", 87, True),
        ("Beauty", 85, True),
        ("Fashion", 84, False),
        ("DIY", 76, False),
        ("Pets", 79, False),
        ("Parenting", 72, False),
        ("Kids", 71, False),
        ("Personal Development", 80, True),
        ("Lifestyle", 70, False),
    ],
    "Entertainment": [
        ("Gaming", 96, True),
        ("Music", 92, True),
        ("Sports", 88, True),
        ("Entertainment", 82, False),
        ("Animation", 80, False),
        ("Podcast", 81, True),
        ("News", 75, False),
        ("Automotive", 78, False),
    ],
    "Healthcare & Medical": [
        ("Healthcare", 75, True),
        ("Hospitals", 72, True),
        ("Medical Practices", 70, True),
        ("Dental Clinics", 70, True),
        ("Mental Health Clinics", 68, True),
        ("Veterinary Clinics", 66, True),
        ("Pharmaceuticals", 68, True),
        ("Biotechnology", 67, True),
    ],
    "Professional Services": [
        ("Consulting Firms", 74, True),
        ("Law Firms", 74, True),
        ("Accounting Firms", 70, True),
        ("Tax Consultants", 66, True),
        ("Insurance Agencies", 68, True),
        ("Recruitment Agencies", 66, True),
        ("HR Consulting", 64, True),
        ("Staffing Firms", 62, True),
        ("Business Coaches", 68, True),
        ("Life Coaches", 66, True),
        ("Professional Speakers", 62, True),
    ],
    "Real Estate & Property": [
        ("Real Estate Agencies", 74, True),
        ("Mortgage Brokers", 66, True),
        ("Property Management", 65, True),
        ("Interior Designers", 68, True),
    ],
    "Construction & Architecture": [
        ("Construction Companies", 70, True),
        ("Architecture Firms", 68, True),
    ],
    "Industry & Manufacturing": [
        ("Manufacturing", 70, True),
        ("Logistics", 68, True),
        ("Transportation", 66, True),
        ("Warehousing", 62, True),
        ("Furniture Manufacturers", 60, True),
        ("Printing Services", 60, True),
        ("Packaging Companies", 60, True),
        ("Chemical Companies", 60, True),
    ],
    "Automotive Business": [
        ("Automotive Dealerships", 68, True),
        ("Auto Repair Shops", 64, True),
    ],
    "Retail & E-commerce": [
        ("E-commerce Stores", 74, True),
        ("Retail Stores", 68, True),
        ("Fashion Brands", 72, True),
        ("Luxury Brands", 68, True),
        ("Jewelry Stores", 64, True),
    ],
    "Beauty & Wellness": [
        ("Beauty Salons", 70, True),
        ("Spas", 66, True),
        ("Barbershops", 64, True),
    ],
    "Fitness & Sports Business": [
        ("Fitness Centers", 72, True),
        ("Gyms", 70, True),
        ("Yoga Studios", 66, True),
        ("Personal Trainers", 68, True),
        ("Sports Clubs", 64, True),
    ],
    "Food & Hospitality": [
        ("Restaurants", 74, True),
        ("Cafes", 68, True),
        ("Hotels", 70, True),
        ("Travel Agencies", 66, True),
        ("Event Management", 66, True),
        ("Wedding Planners", 64, True),
        ("Photography Studios", 66, True),
    ],
    "Education & Training": [
        ("Education", 72, True),
        ("Schools", 68, True),
        ("Colleges", 66, True),
        ("Universities", 66, True),
        ("Coaching Centers", 64, True),
        ("EdTech Companies", 72, True),
    ],
    "Marketing & Media": [
        ("Marketing Agencies", 76, True),
        ("Advertising Agencies", 72, True),
        ("PR Agencies", 66, True),
        ("Media Companies", 70, True),
        ("News Publishers", 66, True),
        ("YouTube Creators", 78, True),
        ("Influencers", 80, True),
        ("Podcasters", 74, True),
        ("Animation Studios", 66, True),
        ("Film Production", 68, True),
        ("Music Labels", 66, True),
    ],
    "IT & Software": [
        ("IT Companies", 72, True),
        ("SaaS Companies", 78, True),
        ("Software Development Firms", 74, True),
        ("Cybersecurity Companies", 72, True),
        ("Cloud Service Providers", 70, True),
        ("AI Startups", 82, True),
        ("Gaming Companies", 72, True),
    ],
    "Finance & FinTech": [
        ("FinTech Companies", 78, True),
        ("Banks", 70, True),
        ("Investment Firms", 70, True),
        ("Wealth Management", 68, True),
        ("Cryptocurrency Companies", 74, True),
    ],
    "Nonprofit & Government": [
        ("Nonprofit Organizations", 64, True),
        ("NGOs", 62, True),
        ("Government Contractors", 60, True),
        ("Religious Organizations", 60, True),
    ],
    "Energy & Utilities": [
        ("Energy Companies", 66, True),
        ("Solar Companies", 68, True),
        ("Oil & Gas", 64, True),
        ("Telecommunications", 66, True),
    ],
    "Agriculture & Food": [
        ("Agriculture", 64, True),
        ("AgriTech", 66, True),
        ("Food Processing", 62, True),
    ],
    "Home Services": [
        ("Home Services", 68, True),
        ("Cleaning Services", 64, True),
        ("Pest Control", 60, True),
        ("Plumbing Services", 62, True),
        ("Electrical Contractors", 62, True),
        ("HVAC Services", 62, True),
        ("Security Companies", 64, True),
    ],
    "Workspace & Franchise": [
        ("Coworking Spaces", 64, True),
        ("Franchises", 66, True),
    ],
    "Tech Verticals": [
        ("SaaS Startups", 65, True),
        ("FinTech", 65, True),
        ("HealthTech", 65, True),
        ("EdTech", 65, True),
        ("LegalTech", 65, True),
        ("PropTech", 65, True),
        ("HRTech", 65, True),
        ("InsurTech", 65, True),
        ("BioTech", 65, True),
        ("CleanTech", 65, True),
        ("ClimateTech", 65, True),
        ("FoodTech", 65, True),
        ("RetailTech", 65, True),
        ("TravelTech", 65, True),
        ("LogisticsTech", 65, True),
    ],
    "Emerging Technology": [
        ("DevOps", 65, True),
        ("Data Analytics", 65, True),
        ("IoT Solutions", 65, True),
        ("Blockchain Companies", 65, True),
        ("Web3 Projects", 65, True),
        ("Game Development Studios", 65, True),
        ("AR/VR Companies", 65, True),
        ("Drone Technology", 65, True),
        ("Space Technology", 65, True),
        ("3D Printing Companies", 65, True),
        ("Quantum Computing Startups", 65, True),
        ("Digital Twin Companies", 65, True),
        ("Smart City Companies", 65, True),
        ("Embedded Systems Companies", 65, True),
        ("Semiconductor Companies", 65, True),
        ("Semiconductor Design Firms", 65, True),
    ],
    "Software & IT Services": [
        ("Software Development Companies", 65, True),
        ("Mobile App Development", 65, True),
        ("Web Development Agencies", 65, True),
        ("IT Consulting Firms", 65, True),
        ("Managed IT Services", 65, True),
        ("ERP Consultants", 65, True),
        ("CRM Consultants", 65, True),
        ("Automation Agencies", 65, True),
        ("No-Code Agencies", 65, True),
        ("Low-Code Agencies", 65, True),
        ("AI Automation Agencies", 65, True),
        ("API Companies", 65, True),
        ("Open Source Companies", 65, True),
        ("Developer Tools Companies", 65, True),
        ("QA Testing Companies", 65, True),
    ],
    "Creative & Marketing Agencies": [
        ("Digital Marketing Agencies", 65, True),
        ("SEO Agencies", 65, True),
        ("Branding Agencies", 65, True),
        ("Video Production Companies", 65, True),
        ("UI/UX Design Agencies", 65, True),
        ("Influencer Agencies", 65, True),
        ("Talent Management Agencies", 65, True),
        ("Signage Companies", 65, True),
    ],
    "Business & Consulting": [
        ("Business Consultants", 65, True),
        ("Management Consultants", 65, True),
        ("BPO Companies", 65, True),
        ("Call Centers", 65, True),
        ("Virtual Assistant Agencies", 65, True),
        ("Corporate Training Companies", 65, True),
        ("Leadership Coaches", 65, True),
        ("Sales Trainers", 65, True),
        ("Public Speakers", 65, True),
        ("Market Research Companies", 65, True),
        ("Survey Companies", 65, True),
        ("Customer Experience Agencies", 65, True),
        ("Loyalty Program Providers", 65, True),
    ],
    "Real Estate & Construction": [
        ("Property Developers", 65, True),
        ("Architects", 65, True),
        ("Civil Engineers", 65, True),
        ("Smart Home Companies", 65, True),
    ],
    "Automotive & Mobility": [
        ("Electric Vehicle Dealers", 65, True),
        ("Automobile Dealers", 65, True),
        ("Car Rental Companies", 65, True),
        ("Fleet Management", 65, True),
        ("EV Charging Companies", 65, True),
    ],
    "Energy & Environment": [
        ("Solar Energy Companies", 65, True),
        ("Renewable Energy Companies", 65, True),
        ("Water Treatment Companies", 65, True),
        ("Waste Management Companies", 65, True),
        ("Recycling Companies", 65, True),
    ],
    "Travel & Hospitality": [
        ("Tour Operators", 65, True),
        ("Resorts", 65, True),
        ("Homestays", 65, True),
        ("Cloud Kitchens", 65, True),
        ("Catering Services", 65, True),
        ("Event Management Companies", 65, True),
    ],
    "Health & Wellness": [
        ("Fitness Coaches", 65, True),
        ("Nutritionists", 65, True),
        ("Clinics", 65, True),
        ("Pharmacies", 65, True),
        ("Diagnostic Labs", 65, True),
        ("Medical Equipment Suppliers", 65, True),
    ],
    "Consumer Brands": [
        ("Cosmetics Brands", 65, True),
        ("Skincare Brands", 65, True),
        ("Jewelry Brands", 65, True),
        ("Watch Brands", 65, True),
        ("Home Decor Brands", 65, True),
        ("Pet Care Brands", 65, True),
        ("Baby Products Brands", 65, True),
        ("Toy Manufacturers", 65, True),
        ("Organic Food Brands", 65, True),
        ("Beverage Companies", 65, True),
        ("FMCG Brands", 65, True),
        ("Consumer Electronics Brands", 65, True),
    ],
    "E-commerce & Retail": [
        ("Amazon Sellers", 65, True),
        ("Shopify Stores", 65, True),
        ("D2C Brands", 65, True),
        ("Wholesale Distributors", 65, True),
        ("Import Export Businesses", 65, True),
        ("Subscription Box Companies", 65, True),
    ],
    "Manufacturing & Industrial": [
        ("Manufacturing Companies", 65, True),
        ("Textile Mills", 65, True),
        ("Chemical Manufacturers", 65, True),
        ("Plastic Manufacturers", 65, True),
        ("Electronics Manufacturers", 65, True),
        ("Apparel Manufacturers", 65, True),
        ("Printing Companies", 65, True),
        ("Printing Presses", 65, True),
        ("Industrial Automation Companies", 65, True),
        ("Smart Factory Solutions", 65, True),
        ("CNC Manufacturing Companies", 65, True),
        ("Aerospace Companies", 65, True),
        ("Marine Engineering Companies", 65, True),
        ("Mining Companies", 65, True),
        ("Oil & Gas Companies", 65, True),
        ("Defense Contractors", 65, True),
    ],
    "Logistics & Supply Chain": [
        ("Shipping Companies", 65, True),
        ("Freight Forwarders", 65, True),
        ("Warehousing Companies", 65, True),
        ("Supply Chain Companies", 65, True),
        ("Export Houses", 65, True),
        ("Import Agencies", 65, True),
    ],
    "Finance & Investment": [
        ("Venture Capital Firms", 65, True),
        ("Angel Investors", 65, True),
        ("Private Equity Firms", 65, True),
        ("Family Offices", 65, True),
        ("Startup Incubators", 65, True),
        ("Business Accelerators", 65, True),
        ("Financial Advisors", 65, True),
        ("Wealth Management Firms", 65, True),
        ("Cryptocurrency Exchanges", 65, True),
        ("Payment Gateway Providers", 65, True),
    ],
    "Education & Coaching": [
        ("Online Course Creators", 65, True),
        ("Coaching Institutes", 65, True),
        ("Language Institutes", 65, True),
        ("Music Academies", 65, True),
        ("Dance Academies", 65, True),
        ("Education Consultants", 65, True),
        ("Immigration Consultants", 65, True),
        ("Study Abroad Consultants", 65, True),
        ("Visa Consultants", 65, True),
    ],
    "Media & Publishing": [
        ("News Portals", 65, True),
        ("Podcast Networks", 65, True),
        ("Film Production Houses", 65, True),
        ("Record Studios", 65, True),
        ("Book Publishers", 65, True),
        ("Telecom Companies", 65, True),
        ("Internet Service Providers", 65, True),
    ],
    "Local & Professional Services": [
        ("Security Services", 65, True),
        ("Facility Management", 65, True),
        ("Pest Control Services", 65, True),
        ("Laundry Services", 65, True),
        ("Home Maintenance Companies", 65, True),
        ("HVAC Companies", 65, True),
        ("Landscaping Companies", 65, True),
        ("Translation Agencies", 65, True),
        ("Localization Companies", 65, True),
    ],
    "Nonprofit & Workspace": [
        ("Non-Profit Organizations", 65, True),
        ("Research Organizations", 65, True),
        ("Co-working Spaces", 65, True),
        ("Franchise Businesses", 65, True),
    ],
    "Artisan & Handmade": [
        ("Artisan Businesses", 65, True),
        ("Handicraft Exporters", 65, True),
    ],
}


def iter_catalog():
    """Yield (name, category, popularity, recommended) for every niche."""
    for category, items in CATALOG.items():
        for name, popularity, recommended in items:
            yield name, category, popularity, recommended
