"""Curated YouTube niche catalog (seed data).

This is the single place to extend the recommended niches. On startup the app
seeds the `niches` table from here if it is empty; the API serves from the DB so
niches are fully backend/database-driven and extensible without a frontend change.
"""
from __future__ import annotations

# category -> [(name, popularity, recommended)]
CATALOG: dict[str, list[tuple[str, int, bool]]] = {
    "Technology": [
        ("Artificial Intelligence", 98, True),
        ("Machine Learning", 92, True),
        ("Programming", 95, True),
        ("Web Development", 90, True),
        ("Mobile Development", 82, False),
        ("Software Development", 88, True),
        ("Cybersecurity", 86, True),
        ("Cloud Computing", 80, False),
        ("Data Science", 89, True),
        ("AI Tools", 94, True),
        ("Robotics", 72, False),
        ("Engineering", 70, False),
    ],
    "Business": [
        ("Entrepreneurship", 91, True),
        ("Marketing", 90, True),
        ("Finance", 88, True),
        ("Investing", 87, True),
        ("Real Estate", 78, False),
        ("Startups", 85, True),
        ("Sales", 75, False),
        ("E-commerce", 84, True),
        ("Crypto", 83, True),
        ("B2B SaaS", 74, False),
        ("Productivity", 79, False),
    ],
    "Education": [
        ("Online Learning", 80, True),
        ("Science", 82, True),
        ("Mathematics", 74, False),
        ("History", 72, False),
        ("Language Learning", 77, False),
        ("Documentary", 70, False),
    ],
    "Health & Fitness": [
        ("Fitness", 90, True),
        ("Nutrition", 84, True),
        ("Yoga", 76, False),
        ("Mental Health", 82, True),
        ("Bodybuilding", 78, False),
    ],
    "Lifestyle": [
        ("Travel", 88, True),
        ("Photography", 83, True),
        ("Cooking", 87, True),
        ("Beauty", 85, True),
        ("Fashion", 84, False),
        ("DIY", 76, False),
        ("Pets", 79, False),
        ("Parenting", 72, False),
        ("Kids", 71, False),
        ("Personal Development", 80, True),
        ("Lifestyle", 70, False),
    ],
    "Entertainment": [
        ("Gaming", 96, True),
        ("Music", 92, True),
        ("Sports", 88, True),
        ("Entertainment", 82, False),
        ("Animation", 80, False),
        ("Podcast", 81, True),
        ("News", 75, False),
        ("Automotive", 78, False),
    ],
    "Healthcare & Medical": [
        ("Healthcare", 75, True),
        ("Hospitals", 72, True),
        ("Medical Practices", 70, True),
        ("Dental Clinics", 70, True),
        ("Mental Health Clinics", 68, True),
        ("Veterinary Clinics", 66, True),
        ("Pharmaceuticals", 68, True),
        ("Biotechnology", 67, True),
    ],
    "Professional Services": [
        ("Consulting Firms", 74, True),
        ("Law Firms", 74, True),
        ("Accounting Firms", 70, True),
        ("Tax Consultants", 66, True),
        ("Insurance Agencies", 68, True),
        ("Recruitment Agencies", 66, True),
        ("HR Consulting", 64, True),
        ("Staffing Firms", 62, True),
        ("Business Coaches", 68, True),
        ("Life Coaches", 66, True),
        ("Professional Speakers", 62, True),
    ],
    "Real Estate & Property": [
        ("Real Estate Agencies", 74, True),
        ("Mortgage Brokers", 66, True),
        ("Property Management", 65, True),
        ("Interior Designers", 68, True),
    ],
    "Construction & Architecture": [
        ("Construction Companies", 70, True),
        ("Architecture Firms", 68, True),
    ],
    "Industry & Manufacturing": [
        ("Manufacturing", 70, True),
        ("Logistics", 68, True),
        ("Transportation", 66, True),
        ("Warehousing", 62, True),
        ("Furniture Manufacturers", 60, True),
        ("Printing Services", 60, True),
        ("Packaging Companies", 60, True),
        ("Chemical Companies", 60, True),
    ],
    "Automotive Business": [
        ("Automotive Dealerships", 68, True),
        ("Auto Repair Shops", 64, True),
    ],
    "Retail & E-commerce": [
        ("E-commerce Stores", 74, True),
        ("Retail Stores", 68, True),
        ("Fashion Brands", 72, True),
        ("Luxury Brands", 68, True),
        ("Jewelry Stores", 64, True),
    ],
    "Beauty & Wellness": [
        ("Beauty Salons", 70, True),
        ("Spas", 66, True),
        ("Barbershops", 64, True),
    ],
    "Fitness & Sports Business": [
        ("Fitness Centers", 72, True),
        ("Gyms", 70, True),
        ("Yoga Studios", 66, True),
        ("Personal Trainers", 68, True),
        ("Sports Clubs", 64, True),
    ],
    "Food & Hospitality": [
        ("Restaurants", 74, True),
        ("Cafes", 68, True),
        ("Hotels", 70, True),
        ("Travel Agencies", 66, True),
        ("Event Management", 66, True),
        ("Wedding Planners", 64, True),
        ("Photography Studios", 66, True),
    ],
    "Education & Training": [
        ("Education", 72, True),
        ("Schools", 68, True),
        ("Colleges", 66, True),
        ("Universities", 66, True),
        ("Coaching Centers", 64, True),
        ("EdTech Companies", 72, True),
    ],
    "Marketing & Media": [
        ("Marketing Agencies", 76, True),
        ("Advertising Agencies", 72, True),
        ("PR Agencies", 66, True),
        ("Media Companies", 70, True),
        ("News Publishers", 66, True),
        ("YouTube Creators", 78, True),
        ("Influencers", 80, True),
        ("Podcasters", 74, True),
        ("Animation Studios", 66, True),
        ("Film Production", 68, True),
        ("Music Labels", 66, True),
    ],
    "IT & Software": [
        ("IT Companies", 72, True),
        ("SaaS Companies", 78, True),
        ("Software Development Firms", 74, True),
        ("Cybersecurity Companies", 72, True),
        ("Cloud Service Providers", 70, True),
        ("AI Startups", 82, True),
        ("Gaming Companies", 72, True),
    ],
    "Finance & FinTech": [
        ("FinTech Companies", 78, True),
        ("Banks", 70, True),
        ("Investment Firms", 70, True),
        ("Wealth Management", 68, True),
        ("Cryptocurrency Companies", 74, True),
    ],
    "Nonprofit & Government": [
        ("Nonprofit Organizations", 64, True),
        ("NGOs", 62, True),
        ("Government Contractors", 60, True),
        ("Religious Organizations", 60, True),
    ],
    "Energy & Utilities": [
        ("Energy Companies", 66, True),
        ("Solar Companies", 68, True),
        ("Oil & Gas", 64, True),
        ("Telecommunications", 66, True),
    ],
    "Agriculture & Food": [
        ("Agriculture", 64, True),
        ("AgriTech", 66, True),
        ("Food Processing", 62, True),
    ],
    "Home Services": [
        ("Home Services", 68, True),
        ("Cleaning Services", 64, True),
        ("Pest Control", 60, True),
        ("Plumbing Services", 62, True),
        ("Electrical Contractors", 62, True),
        ("HVAC Services", 62, True),
        ("Security Companies", 64, True),
    ],
    "Workspace & Franchise": [
        ("Coworking Spaces", 64, True),
        ("Franchises", 66, True),
    ],
}


def iter_catalog():
    """Yield (name, category, popularity, recommended) for every niche."""
    for category, items in CATALOG.items():
        for name, popularity, recommended in items:
            yield name, category, popularity, recommended
